dotenv: .env

compiler:
  solc:
    version: 0.8.1
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0"
      - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
      - "@nomiclabs=Nomiclabs/buidler@1.3.0"

networks:
  default: hardhat

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - Uniswap/v3-periphery@1.3.0
  - Uniswap/v3-core@1.0.0

wallet:
  mnemonic: ${MNEMONIC}